# Reference:
#https://github.com/pioarduino/platform-espressif32/blob/develop/examples/espidf-arduino-blink/platformio.ini

[platformio]
src_dir = main
boards_dir = boards

[env:unihiker_k10_arcade]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
framework = espidf
board = unihiker_k10_arcade
monitor_speed = 115200
monitor_filters = direct
